Manage audios
AnanUua/bddi-final-project pull request #25
Opened 2023-05-10 18:09 UTC by victorcngo

2023-05-12 22:04 UTC, P4tt4te requested changes
Ecoute c'est vraiment nice en vrai, il y a juste un bug un peu bloquant mais sinon quand ça démarre ça marche bien !

2023-05-12 22:04 UTC, P4tt4te commented on src/components/Experience/Experience.jsx
> +      <AudioManager sceneIndex={scene} pinpointIndex={pinpoint} mapActive={mapActive} />
En gros j'ai réussi à faire marcher l'audio (et quand ça démarre ça à l'air de bien marcher) mais souvent j'avais cette erreur dans la console : 
![image](https://github.com/AnanUua/bddi-final-project/assets/57622377/5dace21d-72a4-4c05-9413-e8593886e38f)
Je ne sais pas trop d'ou ça vient mais à mon avis il doit y avoir un changement de son pendant une requête play ou un truc comme ça.

2023-05-12 22:04 UTC, P4tt4te commented on src/components/Experience/Experience.jsx
> +      <AudioManager sceneIndex={scene} pinpointIndex={pinpoint} mapActive={mapActive} />
Pour faire le bug : 
Lancer l'intro avec commencer et genre spam les boutons assez rapidement et quand tu arrive dans la première scène tu as ce message avec aucun audio qui ce lance par la suite.

2023-05-13 15:31 UTC, victorcngo commented on src/components/Experience/effects/WindEffect.jsx
> +    // console.log(delta)
ouep, j'allais retirer ça avant de merge t'inquiète :) je vais le laisser pour le moment comme la branche est encore wip, mais tu as raison!

2023-05-13 15:31 UTC, victorcngo commented on src/components/AudioManager/AudioManager.jsx
> +import { useEffect } from "react"
ouep, c'est une bonne idée! c'est pas vraiment un component qui concerne l'affichage ou le rendu, donc suis d'accord!

2023-05-13 15:33 UTC, victorcngo commented on src/components/Experience/Experience.jsx
> +      <AudioManager sceneIndex={scene} pinpointIndex={pinpoint} mapActive={mapActive} />
oh okay! c'est vrai que je n'ai pas testé avec l'intro. j'ai testé en la passant à chaque fois. je vais voir pour régler ça!

2023-05-14 15:01 UTC, victorcngo commented on src/components/Experience/Experience.jsx
> +      <AudioManager sceneIndex={scene} pinpointIndex={pinpoint} mapActive={mapActive} />
hmm, perso je n'arrive pas à reproduire le bug. j'ai beau spam comme un fou. peut-être que j'ai commit quelque chose entre temps qui résout le souci?

j'ai encore le message d'erreur dans la console, mais chez moi ce n'est pas bloquant.

2023-05-15 19:50 UTC, P4tt4te commented on src/components/Experience/Experience.jsx
> +      <AudioManager sceneIndex={scene} pinpointIndex={pinpoint} mapActive={mapActive} />
ok bah en tout cas ça serait quand même nice je pense d'enlever cette erreur de la console histoire d'être sûr mais si tu veux je pourrai retest si besoin.

2023-05-25 13:02 UTC, P4tt4te approved these changes
Bah écoute c'est niquel, d'extérieur rien à dire perso le rendu est incr !

2023-05-25 17:07 UTC, victorcngo commented on src/components/Curtain/Curtain.jsx
> +  return <div className="Curtain"></div>
il pourrait servir à afficher un black screen, éventuellement du texte si besoin ou bien le titre du chapitre en cours?

2023-05-26 02:05 UTC, merged