Implement narrative UI with test audios
AnanUua/bddi-final-project pull request #3
Opened 2023-03-08 23:27 UTC by victorcngo

je n'ai pas encore fini de C/C tout le code de mon POC (il me reste les audios et l'interface à l'intérieur de l'expérience). ça devrait être fait rapidement, mais je voulais déjà créer la PR.

il faudra aussi que je passe le fichier Introduction.scss en Introduction.module.scss et faire les changements nécessaires. je dois juste voir comment je peux combiner les modules SCSS avec la syntaxe BEM.

2023-03-09 09:51 UTC, P4tt4te requested changes
Nice, je t'ai fait quelques retours à voir ensemble.

2023-03-09 09:51 UTC, P4tt4te commented on src/components/Interface/Interface.scss
> +    border: 0.3rem solid rgb(41, 34, 23);
perso je suis plus de la team à mettre les couleurs en héxa, tu préfère le rgb toi ? 
Mais en vrai c'est pas grave du tout. 

Et d'ailleurs ça serait cool qu'on ait toutes nos couleurs dans les variables du fichier globals.scss mais pas grave du tout.

2023-03-09 09:51 UTC, P4tt4te commented on src/components/Introduction/Introduction.jsx
> +  const splashScreen = () => {
Mettre en sous composant, je pense le mieux est d'avoir un seul rendu par fichier. Après à voir, t'en penses quoi ? 
Et aussi pour les scènes 3d je sais que tout n'est pas bien mis pour l'instant il faudrait un petite refacto aussi de ce côté là donc tranquille.

2023-03-09 10:27 UTC, victorcngo commented on src/components/Interface/Interface.jsx
> +    const buttons = document.querySelectorAll('.buttons button')
oui ne t'en fais pas! c'était juste pour l'interface de debug, histoire d'avoir un truc rapide. mais je vois comment faire ça de manière propre en JSX

2023-03-09 10:29 UTC, victorcngo commented on src/components/Introduction/Introduction.scss
> +.Introduction {
okay, je vois!

2023-03-09 10:33 UTC, victorcngo commented on src/components/Introduction/Introduction.jsx
> +  const splashScreen = () => {
ok pour avoir un seul rendu par fichier!

2023-03-09 10:35 UTC, victorcngo commented on src/components/Introduction/Introduction.jsx
> +          <div className="Introduction__options">{options}</div>
ouaip c'est prévu que je mette que la phrase choisie! faut juste voir quelle anim mettre. j'aurais peut-être gardé la même couleur que le texte précédent, cependant.

2023-03-09 13:21 UTC, P4tt4te commented on src/components/Interface/Interface.scss
> +    border: 0.3rem solid rgb(41, 34, 23);
ah okay

2023-03-21 21:42 UTC, P4tt4te requested changes
Dans l'ensemble c'est nice je trouve ! 
Je t'ai mis quelques com !

2023-03-21 21:42 UTC, P4tt4te commented on package.json
> +    "gsap": "file:gsap-bonus.tgz",
on ajoute gsap finalement ?

2023-03-21 21:42 UTC, P4tt4te commented on package.json
> +    "gsap": "file:gsap-bonus.tgz",
je m'y connais pas en lib d'animation donc à voir si on prend ça ou framer

2023-03-21 21:42 UTC, P4tt4te commented on src/App.jsx
> +  const hasExperienceStarted = useSelector((state) => state.introduction.hasExperienceStarted)
Il me semble que c'est déjà en place sur main donc il va falloir surement rebase ta branche avant de merger et juste vérifier que tout fonctionne (juste hasExperienceStarted est dans le reducer user sur la branche main)

2023-03-21 21:42 UTC, P4tt4te commented on src/components/Introduction/Introduction.jsx
> +            {render()}
En vrai ton code est cool mais je pense que la lisibilité pourrait être amélioré en séparant en sous composants parce que la il y a bcp de logique dans 1 seul composant. En gros React c'est un framework qui est parfait quand ta logique est bien séparer mais il peut devenir très verbeux rapidement si on met tout dans le même composant. 

Par exemple ta fonction render() crée un sous-composant et utilise des props pour passer les infos des states et les fonctions onClick. Je pense que ça va déjà aérer un peu le code de Introduction.

2023-03-21 21:42 UTC, P4tt4te commented on src/components/Introduction/Introduction.jsx
> +            {render()}
Si tu as besoin je pourrais le refactor ou te recorriger ou même peer-programming si tu veux !

2023-03-21 21:55 UTC, victorcngo commented on src/App.jsx
> +  const hasExperienceStarted = useSelector((state) => state.introduction.hasExperienceStarted)
ça marche! j'adapterai tout ça au moment de merge! limite, je me demande même si je pourrai pas modifier le code et faire en sorte que l'introduction mutate plutôt le store user (en stockant les choix du début etc.). à terme, le store introduction ne semble peut-être pas si utile que ça! hasExperienceStarted pourrait juste devenir un state local?

2023-03-21 21:59 UTC, victorcngo commented on package.json
> +    "gsap": "file:gsap-bonus.tgz",
ça pourra assez facilement se retirer si besoin, je l'ai mis au cas où pour tester rapidement (surtout que là j'ai incorporé les plugins bonus, qui sont assez chiants à trouver). je te propose qu'on laisse ça dans le projet le temps du dev (au cas où), et on le retirera quand on aura adopté Framer pour de bon?

2023-03-21 22:00 UTC, P4tt4te commented on package.json
> +    "gsap": "file:gsap-bonus.tgz",
yes ça me va !

2023-03-21 22:02 UTC, P4tt4te commented on src/App.jsx
> +  const hasExperienceStarted = useSelector((state) => state.introduction.hasExperienceStarted)
Parfait !
Yes bien sur, il faut qu'on limite au maximum la complexité du store si on peut.

2023-03-21 22:02 UTC, P4tt4te commented on src/components/Introduction/Introduction.jsx
> +            {render()}
Vasi bah feu

2023-03-27 09:19 UTC, merged